In [1]:
import numpy as np
import pandas as pd

In [2]:
from google.colab import drive
drive.mount('/content/drive')

Mounted at /content/drive

#Preprocesamiento del archivo 'customers.csv'

In [3]:
df_customers = pd.read_csv('/content/drive/MyDrive/Colab Notebooks/fuentes/customers.csv')

In [4]:
df_customers

       Customer ID       Name    Surname Gender   Birthdate
0           752858       Sean  Rodriguez      F  2002-10-20
1            26381   Michelle     Phelps    NaN  1985-10-24
2           305449      Jacob   Williams      M  1981-10-25
3           988259     Nathan     Snyder      M  1977-10-26
4           764762    Crystal      Knapp      F  1951-11-02
...            ...        ...        ...    ...         ...
49995       891845  Christine      Leach      F  1997-10-21
49996       800560       Anna      Allen      F  1999-10-21
49997       133285     Nicole   Franklin      M  1979-10-26
49998       616122      Maria     Keller      M  1981-10-25
49999       832184      Billy     Walker      F  1958-10-31

[50000 rows x 5 columns]

In [5]:
df_customers_copia = df_customers

In [6]:
df_customers_copia

       Customer ID       Name    Surname Gender   Birthdate
0           752858       Sean  Rodriguez      F  2002-10-20
1            26381   Michelle     Phelps    NaN  1985-10-24
2           305449      Jacob   Williams      M  1981-10-25
3           988259     Nathan     Snyder      M  1977-10-26
4           764762    Crystal      Knapp      F  1951-11-02
...            ...        ...        ...    ...         ...
49995       891845  Christine      Leach      F  1997-10-21
49996       800560       Anna      Allen      F  1999-10-21
49997       133285     Nicole   Franklin      M  1979-10-26
49998       616122      Maria     Keller      M  1981-10-25
49999       832184      Billy     Walker      F  1958-10-31

[50000 rows x 5 columns]

In [7]:
df_customers_copia.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 50000 entries, 0 to 49999
Data columns (total 5 columns):
 #   Column       Non-Null Count  Dtype
---  ------       --------------  -----
 0   Customer ID  50000 non-null  int64
 1   Name         50000 non-null  object
 2   Surname      50000 non-null  object
 3   Gender       44953 non-null  object
 4   Birthdate    50000 non-null  object
dtypes: int64(1), object(4)
memory usage: 1.9+ MB

La columna "Gender" tiene datos faltantes.

In [8]:
df_customers_copia.duplicated(subset=['Name','Surname','Gender','Birthdate']).sum()

158

Se detectan 158 registros como duplicados.

In [9]:
customers_duplicated = df_customers_copia.duplicated(['Name','Surname','Gender','Birthdate'])[df_customers_copia.duplicated(['Name','Surname','Gender','Birthdate']) == True].index

In [10]:
customers_duplicated

Int64Index([ 3822,  4530,  4682,  4889,  8032,  9160, 10490, 11331, 11580,
            13576,
            ...
            47915, 48188, 48812, 48851, 49492, 49499, 49558, 49680, 49883,
            49996],
           dtype='int64', length=158)

In [11]:
df_customers_copia = df_customers_copia.drop(customers_duplicated,axis=0)

In [12]:
df_customers_copia

       Customer ID       Name    Surname Gender   Birthdate
0           752858       Sean  Rodriguez      F  2002-10-20
1            26381   Michelle     Phelps    NaN  1985-10-24
2           305449      Jacob   Williams      M  1981-10-25
3           988259     Nathan     Snyder      M  1977-10-26
4           764762    Crystal      Knapp      F  1951-11-02
...            ...        ...        ...    ...         ...
49994       197066     George     Cooper      F  1998-10-21
49995       891845  Christine      Leach      F  1997-10-21
49997       133285     Nicole   Franklin      M  1979-10-26
49998       616122      Maria     Keller      M  1981-10-25
49999       832184      Billy     Walker      F  1958-10-31

[49842 rows x 5 columns]

In [13]:
df_customers_copia.reset_index(drop=True, inplace=True)

In [14]:
df_customers_copia

       Customer ID       Name    Surname Gender   Birthdate
0           752858       Sean  Rodriguez      F  2002-10-20
1            26381   Michelle     Phelps    NaN  1985-10-24
2           305449      Jacob   Williams      M  1981-10-25
3           988259     Nathan     Snyder      M  1977-10-26
4           764762    Crystal      Knapp      F  1951-11-02
...            ...        ...        ...    ...         ...
49837       197066     George     Cooper      F  1998-10-21
49838       891845  Christine      Leach      F  1997-10-21
49839       133285     Nicole   Franklin      M  1979-10-26
49840       616122      Maria     Keller      M  1981-10-25
49841       832184      Billy     Walker      F  1958-10-31

[49842 rows x 5 columns]

In [15]:
df_customers_copia.duplicated(subset=['Name','Surname','Gender','Birthdate']).sum()

0

Los registros duplicados ya fueron eliminados. Ahora queda transformar la columna de "Gender".

No se eliminaran los registros con el valor "NaN" en "Gender" porque es importante tenerlos en cuenta en el anÃ¡lisis. Se reemplazarÃ¡ el valor faltante por un string.

In [16]:
df_customers_copia['Gender'].replace(np.NaN,'Sin especificar',inplace=True)

In [17]:
df_customers_copia

       Customer ID       Name    Surname           Gender   Birthdate
0           752858       Sean  Rodriguez                F  2002-10-20
1            26381   Michelle     Phelps  Sin especificar  1985-10-24
2           305449      Jacob   Williams                M  1981-10-25
3           988259     Nathan     Snyder                M  1977-10-26
4           764762    Crystal      Knapp                F  1951-11-02
...            ...        ...        ...              ...         ...
49837       197066     George     Cooper                F  1998-10-21
49838       891845  Christine      Leach                F  1997-10-21
49839       133285     Nicole   Franklin                M  1979-10-26
49840       616122      Maria     Keller                M  1981-10-25
49841       832184      Billy     Walker                F  1958-10-31

[49842 rows x 5 columns]

In [18]:
df_customers_copia.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 49842 entries, 0 to 49841
Data columns (total 5 columns):
 #   Column       Non-Null Count  Dtype
---  ------       --------------  -----
 0   Customer ID  49842 non-null  int64
 1   Name         49842 non-null  object
 2   Surname      49842 non-null  object
 3   Gender       49842 non-null  object
 4   Birthdate    49842 non-null  object
dtypes: int64(1), object(4)
memory usage: 1.9+ MB

Ya no quedan registros faltantes ni duplicados.

Se exporta el DataFrame.

In [42]:
df_customers_copia.to_csv('/content/drive/MyDrive/Colab Notebooks/fuentes/customers_clean.csv', index=False)

#Preprocesamiento del archivo 'merchants.csv'

In [19]:
df_merchants = pd.read_csv('/content/drive/MyDrive/Colab Notebooks/fuentes/merchants.csv')

In [20]:
df_merchants

       MerchantID                 Merchant Name     Category
0               1                 Smith-Russell     Cosmetic
1               2        Peck, Spence and Young       Travel
2               3                    Steele Inc     Clothing
3               4    Wilson, Wilson and Russell     Cosmetic
4               5                 Palmer-Hinton  Electronics
...           ...                           ...          ...
36934       43874      Wallace, Kim and Rosales   Restaurant
36935       43876                 Knapp-Calhoun     Cosmetic
36936       43877  Cantrell, Haynes and Ballard       Market
36937       43878     Wilson, Jackson and Beard       Market
36938       43879                     Combs LLC       Market

[36939 rows x 3 columns]

In [21]:
df_merchants_copia = df_merchants

In [22]:
df_merchants_copia.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 36939 entries, 0 to 36938
Data columns (total 3 columns):
 #   Column         Non-Null Count  Dtype
---  ------         --------------  -----
 0   MerchantID     36939 non-null  int64
 1   Merchant Name  36939 non-null  object
 2   Category       36939 non-null  object
dtypes: int64(1), object(2)
memory usage: 865.9+ KB

No tiene registros faltantes. Lo Ãºnico que se harÃ¡ es el tratado de duplicados.

In [23]:
df_merchants_copia.duplicated(subset=['Merchant Name','Category']).sum()

0

No existen registros duplicados.

No es necesario exportar el DataFrame ya que no se realizÃ³ ningun cambio.

#Preprocesamiento del archivo 'transactions_ecommerce.csv'

In [24]:
df_transactions = pd.read_csv('/content/drive/MyDrive/Colab Notebooks/fuentes/transactions_ecommerce.csv')

In [25]:
df_transactions

       TransactionID  Customer_ID        Date  MerchantID  Transaction_Amount
0                  1       752858  2023-04-03           1                3547
1                  2        26381  2023-07-17           2              255272
2                  3       305449  2023-09-20           3               11597
3                  4       988259  2023-01-11           4                1131
4                  5       764762  2023-06-13           5                6221
...              ...          ...         ...         ...                 ...
53925          53926       891845  2023-08-30       16155               10874
53926          53927       800560  2023-05-03       43876               13366
53927          53928       133285  2023-02-12       43877               46429
53928          53929       616122  2023-03-25       43878               47257
53929          53930       832184  2023-05-20       43879               27067

[53930 rows x 5 columns]

In [26]:
df_transactions_copia = df_transactions

In [27]:
df_transactions_copia.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 53930 entries, 0 to 53929
Data columns (total 5 columns):
 #   Column              Non-Null Count  Dtype
---  ------              --------------  -----
 0   TransactionID       53930 non-null  int64
 1   Customer_ID         53930 non-null  int64
 2   Date                53930 non-null  object
 3   MerchantID          53930 non-null  int64
 4   Transaction_Amount  53930 non-null  int64
dtypes: int64(4), object(1)
memory usage: 2.1+ MB

No hay registros faltantes.

In [28]:
df_transactions_copia.duplicated(subset=['Customer_ID','Date','MerchantID','Transaction_Amount']).sum()

3930

Hay 3930 registros duplicados.

In [29]:
transactions_duplicated = df_transactions_copia.duplicated(subset=['Customer_ID','Date','MerchantID','Transaction_Amount'])[df_transactions_copia.duplicated(subset=['Customer_ID','Date','MerchantID','Transaction_Amount']) == True].index

In [30]:
transactions_duplicated

Int64Index([50000, 50001, 50002, 50003, 50004, 50005, 50006, 50007, 50008,
            50009,
            ...
            53920, 53921, 53922, 53923, 53924, 53925, 53926, 53927, 53928,
            53929],
           dtype='int64', length=3930)

In [31]:
df_transactions_copia = df_transactions_copia.drop(transactions_duplicated,axis=0)

In [32]:
df_transactions_copia

       TransactionID  Customer_ID        Date  MerchantID  Transaction_Amount
0                  1       752858  2023-04-03           1                3547
1                  2        26381  2023-07-17           2              255272
2                  3       305449  2023-09-20           3               11597
3                  4       988259  2023-01-11           4                1131
4                  5       764762  2023-06-13           5                6221
...              ...          ...         ...         ...                 ...
49995          49996       891845  2023-08-30       16155               10874
49996          49997       800560  2023-05-03       43876               13366
49997          49998       133285  2023-02-12       43877               46429
49998          49999       616122  2023-03-25       43878               47257
49999          50000       832184  2023-05-20       43879               27067

[50000 rows x 5 columns]

In [33]:
df_transactions_copia.duplicated(subset=['Customer_ID','Date','MerchantID','Transaction_Amount']).sum()

0

Ya no hay registros duplicados.

Se exporta el DataFrame.

In [43]:
df_transactions_copia.to_csv('/content/drive/MyDrive/Colab Notebooks/fuentes/transactions_ecommerce_clean.csv', index=False)

#Preprocesamiento del archivo 'customers_purchasing_power.csv'

In [34]:
df_cpp = pd.read_csv('/content/drive/MyDrive/Colab Notebooks/fuentes/customers_purchasing_power.csv')

In [35]:
df_cpp

       Customer ID Purchasing Power
0           752858              Low
1            26381              Low
2           305449              Low
3           988259              Low
4           764762              Low
...            ...              ...
49995       891845              Low
49996       800560              Mid
49997       133285              Mid
49998       616122              Mid
49999       832184             High

[50000 rows x 2 columns]

In [36]:
df_cpp_copia = df_cpp

In [37]:
df_cpp_copia.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 50000 entries, 0 to 49999
Data columns (total 2 columns):
 #   Column            Non-Null Count  Dtype
---  ------            --------------  -----
 0   Customer ID       50000 non-null  int64
 1   Purchasing Power  50000 non-null  object
dtypes: int64(1), object(1)
memory usage: 781.4+ KB

No hay registros faltantes.

In [38]:
df_cpp_copia.duplicated().sum()

0

No hay registros duplicados.

No es necesario exportar el DataFrame ya que no se realizÃ³ ningun cambio.